import {
  GameType,
  HandStatus,
  SeatStatus,
  Street,
  TableStatus,
} from "@mix-online/shared";
import type { TableDetailRecord } from "../../table-detail";
import type { TableDetailRepository } from "./contract";

const MVP_TABLE_DETAILS: TableDetailRecord[] = [
  {
    tableId: "a1b2c3d4-0001-4000-8000-000000000001",
    tableName: "Table 1",
    status: TableStatus.WAITING,
    gameType: GameType.STUD_HI,
    mixIndex: 0,
    handsSinceRotation: 0,
    dealerSeatNo: 1,
    smallBet: 20,
    bigBet: 40,
    ante: 5,
    bringIn: 10,
    minPlayers: 2,
    maxPlayers: 6,
    seats: [
      {
        seatNo: 1,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 2,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 3,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 4,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 5,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 6,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
    ],
    currentHand: null,
  },
  {
    tableId: "a1b2c3d4-0002-4000-8000-000000000002",
    tableName: "Table 2",
    status: TableStatus.BETTING,
    gameType: GameType.RAZZ,
    mixIndex: 1,
    handsSinceRotation: 3,
    dealerSeatNo: 4,
    smallBet: 20,
    bigBet: 40,
    ante: 5,
    bringIn: 10,
    minPlayers: 2,
    maxPlayers: 6,
    seats: [
      {
        seatNo: 1,
        status: SeatStatus.ACTIVE,
        userId: "b1b2c3d4-1111-4111-8111-111111111111",
        displayName: "Alice",
        stack: 1600,
        isYou: true,
        joinedAt: "2026-02-11T11:30:00.000Z",
        disconnectStreak: 0,
      },
      {
        seatNo: 2,
        status: SeatStatus.ACTIVE,
        userId: "b1b2c3d4-2222-4222-8222-222222222222",
        displayName: "Bob",
        stack: 1420,
        isYou: false,
        joinedAt: "2026-02-11T11:31:00.000Z",
        disconnectStreak: 0,
      },
      {
        seatNo: 3,
        status: SeatStatus.SIT_OUT,
        userId: "b1b2c3d4-3333-4333-8333-333333333333",
        displayName: "Carol",
        stack: 980,
        isYou: false,
        joinedAt: "2026-02-11T11:32:00.000Z",
        disconnectStreak: 0,
      },
      {
        seatNo: 4,
        status: SeatStatus.DISCONNECTED,
        userId: "b1b2c3d4-4444-4444-8444-444444444444",
        displayName: "Dave",
        stack: 1240,
        isYou: false,
        joinedAt: "2026-02-11T11:33:00.000Z",
        disconnectStreak: 1,
      },
      {
        seatNo: 5,
        status: SeatStatus.EMPTY,
        userId: null,
        displayName: null,
        stack: 0,
        isYou: false,
        joinedAt: null,
        disconnectStreak: null,
      },
      {
        seatNo: 6,
        status: SeatStatus.LEAVE_PENDING,
        userId: "b1b2c3d4-6666-4666-8666-666666666666",
        displayName: "Eve",
        stack: 300,
        isYou: false,
        joinedAt: "2026-02-11T11:34:00.000Z",
        disconnectStreak: 0,
      },
    ],
    currentHand: {
      handId: "c1b2c3d4-0002-4000-8000-000000000099",
      handNo: 99,
      status: HandStatus.IN_PROGRESS,
      street: Street.FIFTH,
      potTotal: 430,
      toActSeatNo: 2,
      actionDeadlineAt: "2026-02-11T12:40:00.000Z",
    },
  },
];

export const createMvpTableDetailRepository = (): TableDetailRepository => {
  return {
    async getById(tableId) {
      return (
        MVP_TABLE_DETAILS.find((table) => table.tableId === tableId) ?? null
      );
    },
  };
};
